name = "smp modpack"
author = "Gurkan <hello@gurkz.me>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12dc50be3b497879b6f91de6a0faf7440cf63a327c3e61e917d6bee35fc80860"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
