name = "gurkz SMP modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8329dcfb942ad2f5df01524466576b239b18db78c5a408b635e3a436ee5a2dd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.21.2", "1.21.3"]
