name = "smp modpack"
author = "Gurkan <hello@gurkz.me>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de2601578f638839c941a692c04d5fe9b613c9ecf931189fb1e2fc24336526e2"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
