name = "gurkz SMP modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "622af4ee2fd6eeb4b538b25fc66f978d5f4dc173a94f8a3157e49984bdd35d0a"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
