name = "gurkz SMP modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8543c68b65d6fc987d30fce1aa9037cca906ad818522b55e9d656bc927360d3c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.21.2", "1.21.3"]
