name = "gurkz SMP modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171fe9478a32be80ed2f7c23206575250193a1d22acce7a679b1a3fa80eabc01"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.21.2", "1.21.3"]
