name = "smp"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6fc63328c6817a04c3057d82908a56ce8762a040b8705a93defdb6fa44f1dab"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
