name = "gurkz SMP modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b24bdf02d65fd08d4f718bff3baeadd7883c2884f64fac6282d5664a7d84af1"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.21.2", "1.21.3"]
